name: Post to Bluesky

on:
  #schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:  # Allow manual triggering

jobs:
  post:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install feedparser atproto

      - name: Run script
        env:
          RSS_FEED_URL: ${{ secrets.RSS_FEED_URL }}
          BSKY_HANDLE: ${{ secrets.BSKY_HANDLE }}
          BSKY_APP_PASSWORD: ${{ secrets.BSKY_APP_PASSWORD }}
        run: python post_to_bluesky.py
